#!/bin/bash

if [ ! -e ../../scripts/helper/parameters.sh ]; then
	echo "ERROR: $0 is not properly alligned with GH project ocp-power-automation/ocs-upi-kvm"
	exit 1
fi

set -e

pushd ../../scripts

export PLATFORM=powervs

source helper/parameters.sh

popd

pushd ../$OCP_PROJECT

ARG1=$1
ARG2=$2
case "$ARG1" in
	addnode)
                number_of_workers=$(oc get nodes | grep "worker" | wc -l)
                export WORKERS=$(( number_of_workers + $ARG2 ))
		terraform_apply
		;;
        delnode)
                number_of_workers=$(oc get nodes | grep "worker" | wc -l)
                export WORKERS=$(( number_of_workers - $ARG2 ))
                terraform_apply
                ;;
	*)
		echo "ERROR: $0 Invalid argument: arg1=$ARG1"
		exit 1
		;;
esac

popd
