#!/bin/bash

# There are no input arguments.  This script sets up a kvm libvirt host
# server supporting an openshift clusters running in VMs.  This script
# installs the virtualization stack, configures firewall, nftables, dns
# overlays, and haproxy.  This setup assumes the IP addresses that are
# generated by the helpernode playbook.  These values are hardcoded 
# along with the cluster domain, so if the underlying projects change
# this script will have to change as well.

# IMPORTANT: Increment KVM_SETUP_GENCNT if you change code logic in this file

set -e

export WIPE_VERSION=${WIPE_VERSION:=2.3.1-17.15}

if [ ! -e helper/parameters.sh ]; then
	echo "Please invoke from the directory ocs-upi-kvm/scripts"
	exit 1
fi

yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-$(rpm -E %rhel).noarch.rpm
yum -y install kernel dracut systemd dbus powerpc-utils net-tools nftables
yum -y install wget git patch gcc-c++ make libgcrypt yum-utils ansible tmux
yum -y module install virt container-tools
yum -y install libvirt libvirt-devel qemu-kvm libguestfs libguestfs-tools virt-install 
yum -y install python3-libvirt haproxy jq

# Workaround bad SELinux labeling of virt.module after installing rhel 8.3 packages above

restorecon -Rv /etc/dnf

source helper/parameters.sh

wipe_installed=$(rpm -q wipe || true)
if [[ ! "$wipe_installed" =~ $WIPE_VERSION ]]; then
	pushd $WORKSPACE
	rm -f wipe-$WIPE_VERSION.ppc64le.rpm
	wget -nv http://rpmfind.net/linux/opensuse/ports/ppc/tumbleweed/repo/oss/ppc64le/wipe-$WIPE_VERSION.ppc64le.rpm
	yum -y localinstall wipe-$WIPE_VERSION.ppc64le.rpm
	popd
fi

# Enable IP Forwarding

sysctl net.ipv4.ip_forward
sysctl net.ipv4.ip_forward=1
echo "net.ipv4.ip_forward = 1" | tee /etc/sysctl.d/99-ipforward.conf
sysctl -p /etc/sysctl.d/99-ipforward.conf

# Enable TCP access for libvirtd

sed -i 's/^LIBVIRTD_ARGS=\"--timeout 120\"/#LIBVIRTD_ARGS=\"--timeout 120\"/' /etc/sysconfig/libvirtd
sed -i 's/#LIBVIRTD_ARGS=\"--listen\"/LIBVIRTD_ARGS=\"--listen\"/' /etc/sysconfig/libvirtd
sed -i 's/#listen_tls = 0/listen_tls = 0/' /etc/libvirt/libvirtd.conf
sed -i 's/#listen_tcp = 1/listen_tcp = 1/' /etc/libvirt/libvirtd.conf
sed -i 's/#auth_tcp = "sasl"/auth_tcp = "none"/' /etc/libvirt/libvirtd.conf
sed -i 's/#tcp_port = "16509"/tcp_port = "16509"/' /etc/libvirt/libvirtd.conf

systemctl stop libvirtd
systemctl mask libvirtd.socket libvirtd-ro.socket libvirtd-admin.socket libvirtd-tcp.socket libvirtd-tls.socket
systemctl enable libvirtd
systemctl start libvirtd

# Allow connections to the libvirt daemon from the IP range used by the cluster.  Persist nftable via systemd

systemctl enable nftables
systemctl restart nftables

if [ ! -e /etc/sysconfig/nftables.conf.orig ]; then
	cp /etc/sysconfig/nftables.conf /etc/sysconfig/nftables.conf.orig
	nft insert rule ip filter INPUT ip saddr $CLUSTER_CIDR ip daddr 192.168.122.1 tcp dport 16509 counter accept comment \"Allow insecure libvirt clients\"
	nft list ruleset >/etc/sysconfig/nftables.conf
fi

# This is being deprecated and produces warning messages

sed -i 's/AllowZoneDrifting=yes/AllowZoneDrifting=no/' /etc/firewalld/firewalld.conf

firewall-cmd --zone=public --add-service=rpc-bind  --permanent
firewall-cmd --zone=public --add-service=mountd    --permanent
firewall-cmd --zone=public --add-service=nfs       --permanent
firewall-cmd --zone=public --add-port=53/tcp       --permanent
firewall-cmd --zone=public --add-port=53/udp       --permanent
firewall-cmd --zone=public --add-port=80/tcp       --permanent  # HAProxy
firewall-cmd --zone=public --add-port=443/tcp      --permanent  # HAProxy
firewall-cmd --zone=public --add-port=623/udp      --permanent  # Remote Management and Control Protocol (ipmi / bmc)
firewall-cmd --zone=public --add-port=6443/tcp     --permanent  # HAProxy
firewall-cmd --zone=public --add-port=22623/tcp    --permanent  # HAProxy

firewall-cmd --zone=libvirt --add-service=libvirt  --permanent
firewall-cmd --zone=libvirt --add-service=http     --permanent
firewall-cmd --zone=libvirt --add-service=https    --permanent
firewall-cmd --zone=libvirt --add-service=rpc-bind --permanent
firewall-cmd --zone=libvirt --add-port=53/tcp      --permanent
firewall-cmd --zone=libvirt --add-port=53/udp      --permanent
firewall-cmd --zone=libvirt --add-port=623/udp     --permanent	# RMCP (ipmi / bmc)
firewall-cmd --zone=libvirt --add-port=953/tcp     --permanent	# named bind9

firewall-cmd --reload

# Setup the DNS overlay for the cluster

echo -e "[main]\ndns=dnsmasq" | tee /etc/NetworkManager/conf.d/openshift.conf
echo server=/$CLUSTER_DOMAIN/$BASTION_IP | tee /etc/NetworkManager/dnsmasq.d/openshift.conf

systemctl restart NetworkManager
systemctl restart firewalld
systemctl restart libvirtd
systemctl restart nftables

set +e

# Setup HAProxy

cat > /etc/firewalld/services/haproxy-http.xml << EOF
<?xml version="1.0" encoding="utf-8"?>
<service>
<short>HAProxy-HTTP</short>
<description>HAProxy load-balancer</description>
<port protocol="tcp" port="80"/>
</service>
EOF

chmod 640 /etc/firewalld/services/haproxy-http.xml
restorecon /etc/firewalld/services/haproxy-http.xml

cat > /etc/firewalld/services/haproxy-https.xml << EOF
<?xml version="1.0" encoding="utf-8"?>
<service>
<short>HAProxy-HTTPS</short>
<description>HAProxy load-balancer</description>
<port protocol="tcp" port="443"/>
</service>
EOF

chmod 640 /etc/firewalld/services/haproxy-https.xml
restorecon /etc/firewalld/services/haproxy-https.xml

if [ ! -e /etc/haproxy/haproxy.cfg.orig ]; then
	cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
fi
cp $WORKSPACE/ocs-upi-kvm/files/haproxy.cfg /etc/haproxy/haproxy.cfg

chmod 644 /etc/haproxy/haproxy.cfg
restorecon -Rv /etc/haproxy

semanage port -ln | grep 6443
if [ "$?" != "0" ]; then
	semanage port -a -t openshift_port_t -p tcp 6443
fi
semanage port -ln | grep 22623
if [ "$?" != "0" ]; then
	semanage port -a -t openshift_port_t -p tcp 22623
fi
setsebool -P haproxy_connect_any=1

systemctl enable haproxy
systemctl restart haproxy
